language: python
cache: pip
sudo: false
python:
  - '3.6'
  - '3.7'
  - '3.8'
script:
  - make test

jobs:
    include: 
    - name: lint
      python: 
        - '3.6'
      script:
        - make lint
    - stage: deploy
      if: branch = master AND type = push
      python: 
        - '3.6'
      script: 
        - flit publish

after_success:
    - codecov --env TRAVIS_OS_NAME || ( sleep 5 && codecov --env TRAVIS_OS_NAME )
     
install:
- pip install -r requirements.txt
