language: python
cache: pip
sudo: false

jobs:
    include: 
    - name: lint
      stage: lint/unit
      script:
        - pylint *.py test/test_*.py
    - name: unit
      script:
        # tempoarily skip the path tests
        - pytest --cov=. -n=2 . 
      python:
        - '3.6'
        - '3.7'
        - '3.8'
    - stage: deploy
      python: 
        - '3.6'
      script: 
        - flit publish
      only:
        - master

after_success:
    - codecov --env TRAVIS_OS_NAME || ( sleep 5 && codecov --env TRAVIS_OS_NAME )
     
install:
- pip install -r requirements.txt
